// templates/vue-vite-shadcn/src/App.vue
<script setup lang="ts">
import { ThemeToggle } from '@/components/common/theme-toggle'
</script>

<template>
  <div class="flex items-center justify-center h-screen">
    <ThemeToggle />
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// templates/react-vite-shadcn/src/App.tsx
import { Button } from '@/components/ui/button'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ThemeToggle } from '@/components/common/theme-toggle'
import { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <ThemeProvider defaultTheme='dark' storageKey='vite-ui-theme'>
      <div className='flex flex-row items-center justify-center h-screen space-x-4'>
        <ThemeToggle />
        <div className='flex flex-row items-center justify-center space-x-4'>
          <Button variant="outline" onClick={() => setCount(count + 1)}>
            Click me
          </Button>
          <p>Count: {count}</p>
        </div>
      </div>
    </ThemeProvider>
  )
}

export default App
